import { NextResponse } from 'next/server';
import { FULL_AI_PROMPT } from '@/components/ImportMarkdownModal';
import { EXPANDED_NODE_PLANNING_PROMPT } from '@/lib/ai-guides/expanded-node-planning';
import { VISION_AI_GUIDANCE_PROMPT_FROM_RESOURCES, VISION_AI_GUIDANCE_PROMPT_FROM_WEBSITE } from '@/lib/ai-guides/vision-guidance';
import {
  POST_GEN_CHECKLIST_ALL,
  POST_GEN_CHECKLIST_COMPLETENESS,
  POST_GEN_CHECKLIST_CONDITIONAL,
  POST_GEN_CHECKLIST_DATA_OBJECTS,
  POST_GEN_CHECKLIST_EXPANDED_NODES,
  POST_GEN_CHECKLIST_IA,
  POST_GEN_CHECKLIST_PROCESS_FLOWS,
  POST_GEN_CHECKLIST_SWIMLANE,
  POST_GEN_CHECKLIST_SYSTEM_FLOW,
  POST_GEN_CHECKLIST_TAGS,
  POST_GEN_CHECKLIST_TECHNICAL,
} from '@/lib/ai-checklists/post-generation-index';
import { POST_GEN_CHECKLIST_VISION_IMPORT } from '@/lib/ai-checklists/post-generation-vision';
import { POST_GEN_CHECKLIST_VISION_COMPONENT_LIBRARY } from '@/lib/ai-checklists/post-generation-vision-component-library';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

function withCors(res: NextResponse) {
  res.headers.set('access-control-allow-origin', '*');
  res.headers.set('access-control-allow-methods', 'GET,OPTIONS');
  res.headers.set('access-control-allow-headers', 'content-type,authorization,x-openai-api-key');
  return res;
}

export async function OPTIONS() {
  return withCors(new NextResponse(null, { status: 204 }));
}

export async function GET() {
  const folder = 'NexusMap AI';

  const startHere = [
    '# NexusMap AI — Start here',
    '',
    'This folder is generated by **NexusMap Sync**.',
    '',
    '## Recommended run order (diagram workflow)',
    '1) Read `01 - Diagram Prompt (FULL).md` and use it as the *only* instruction to the AI for generation.',
    '2) Generate / update your diagram markdown files in your vault.',
    '3) Validate using `10 - Post-generation Checklist (ALL).md`.',
    '4) If you used expanded nodes: use `02 - Expanded Nodes Parking Lot.md` as your second-pass prompt.',
    '5) Re-run the checklist after any fixes.',
    '',
    '## Vision workflow (if you use Vision docs)',
    '1) Pick a prompt: `20 - Vision Prompt A (resources provided).md` or `21 - Vision Prompt B (discover from website).md`.',
    '2) Validate with `22 - Vision Checklist (importability).md` then `23 - Vision Checklist (component library).md`.',
    '',
  ].join('\n');

  const files = [
    { relativePath: `${folder}/00 - Start Here.md`, content: startHere },
    { relativePath: `${folder}/01 - Diagram Prompt (FULL).md`, content: FULL_AI_PROMPT },
    { relativePath: `${folder}/02 - Expanded Nodes Parking Lot.md`, content: EXPANDED_NODE_PLANNING_PROMPT },
    { relativePath: `${folder}/10 - Post-generation Checklist (ALL).md`, content: POST_GEN_CHECKLIST_ALL },
    { relativePath: `${folder}/11 - Checklist - Technical.md`, content: POST_GEN_CHECKLIST_TECHNICAL },
    { relativePath: `${folder}/12 - Checklist - IA.md`, content: POST_GEN_CHECKLIST_IA },
    { relativePath: `${folder}/13 - Checklist - Expanded Nodes.md`, content: POST_GEN_CHECKLIST_EXPANDED_NODES },
    { relativePath: `${folder}/14 - Checklist - Tags.md`, content: POST_GEN_CHECKLIST_TAGS },
    { relativePath: `${folder}/15 - Checklist - Process Flows.md`, content: POST_GEN_CHECKLIST_PROCESS_FLOWS },
    { relativePath: `${folder}/16 - Checklist - System Flow.md`, content: POST_GEN_CHECKLIST_SYSTEM_FLOW },
    { relativePath: `${folder}/17 - Checklist - Conditional.md`, content: POST_GEN_CHECKLIST_CONDITIONAL },
    { relativePath: `${folder}/18 - Checklist - Data Objects.md`, content: POST_GEN_CHECKLIST_DATA_OBJECTS },
    { relativePath: `${folder}/19 - Checklist - Swimlane.md`, content: POST_GEN_CHECKLIST_SWIMLANE },
    { relativePath: `${folder}/19b - Checklist - Completeness.md`, content: POST_GEN_CHECKLIST_COMPLETENESS },
    { relativePath: `${folder}/20 - Vision Prompt A (resources provided).md`, content: VISION_AI_GUIDANCE_PROMPT_FROM_RESOURCES },
    { relativePath: `${folder}/21 - Vision Prompt B (discover from website).md`, content: VISION_AI_GUIDANCE_PROMPT_FROM_WEBSITE },
    { relativePath: `${folder}/22 - Vision Checklist (importability).md`, content: POST_GEN_CHECKLIST_VISION_IMPORT },
    { relativePath: `${folder}/23 - Vision Checklist (component library).md`, content: POST_GEN_CHECKLIST_VISION_COMPONENT_LIBRARY },
  ];

  return withCors(NextResponse.json({ ok: true, files }));
}

