import { POST_GEN_CHECKLIST_TECHNICAL } from './post-generation-technical';
import { POST_GEN_CHECKLIST_IA } from './post-generation-ia';
import { POST_GEN_CHECKLIST_DATA_OBJECTS } from './post-generation-data-objects';
import { POST_GEN_CHECKLIST_CONDITIONAL } from './post-generation-conditional';
import { POST_GEN_CHECKLIST_SWIMLANE } from './post-generation-swimlane';
import { POST_GEN_CHECKLIST_COMPLETENESS } from './post-generation-completeness';
import { POST_GEN_CHECKLIST_PROCESS_FLOWS } from './post-generation-process-flows';

export {
  POST_GEN_CHECKLIST_TECHNICAL,
  POST_GEN_CHECKLIST_IA,
  POST_GEN_CHECKLIST_PROCESS_FLOWS,
  POST_GEN_CHECKLIST_CONDITIONAL,
  POST_GEN_CHECKLIST_DATA_OBJECTS,
  POST_GEN_CHECKLIST_SWIMLANE,
  POST_GEN_CHECKLIST_COMPLETENESS,
};

export const POST_GEN_CHECKLIST_ALL = [
  POST_GEN_CHECKLIST_TECHNICAL,
  POST_GEN_CHECKLIST_IA,
  POST_GEN_CHECKLIST_PROCESS_FLOWS,
  POST_GEN_CHECKLIST_CONDITIONAL,
  POST_GEN_CHECKLIST_DATA_OBJECTS,
  POST_GEN_CHECKLIST_SWIMLANE,
  POST_GEN_CHECKLIST_COMPLETENESS,
].join('\n\n');

