import { EXPANDED_NODE_PLANNING_PROMPT } from '../../../web/lib/ai-guides/expanded-node-planning';
import {
  VISION_AI_GUIDANCE_PROMPT_FROM_RESOURCES,
  VISION_AI_GUIDANCE_PROMPT_FROM_WEBSITE,
} from '../../../web/lib/ai-guides/vision-guidance';
import { POST_GEN_CHECKLIST_ALL } from '../../../web/lib/ai-checklists/post-generation-index';
import { POST_GEN_CHECKLIST_VISION_IMPORT } from '../../../web/lib/ai-checklists/post-generation-vision';
import { POST_GEN_CHECKLIST_VISION_COMPONENT_LIBRARY } from '../../../web/lib/ai-checklists/post-generation-vision-component-library';

export function buildAiGuideMarkdown(): string {
  return [
    '# NexusMap — AI guide (vault copy)',
    '',
    'This file is generated by **NexusMap Sync** so your vault always contains the latest AI guidance/checklists.',
    '',
    '## How to use this vault with AI',
    '- Keep each NexusMap doc as a standalone `.md` file.',
    '- For **note** docs, the Markdown is the document.',
    '- For **vision** docs, include exactly one `visionjson` fenced block.',
    '- For **grid** docs, include exactly one `gridjson` fenced block.',
    '',
    '## Diagram guidance',
    'Diagram generation uses a NexusMap-specific tree format (indentation-based) and additional JSON blocks under a `---` separator.',
    'In the web app, use **Import MD** and the built-in guidance/checklists bundle for the full diagram prompt.',
    '',
    '## Expanded-node parking lot template (optional)',
    EXPANDED_NODE_PLANNING_PROMPT,
    '',
    '## Vision prompt A — design system resources provided',
    VISION_AI_GUIDANCE_PROMPT_FROM_RESOURCES,
    '',
    '## Vision prompt B — discover from website',
    VISION_AI_GUIDANCE_PROMPT_FROM_WEBSITE,
    '',
    '## Post-generation checklist — ALL (combined)',
    POST_GEN_CHECKLIST_ALL,
    '',
    '## Post-generation checklist — Vision importability',
    POST_GEN_CHECKLIST_VISION_IMPORT,
    '',
    '## Post-generation checklist — Vision component library',
    POST_GEN_CHECKLIST_VISION_COMPONENT_LIBRARY,
    '',
  ].join('\n');
}

