import { EXPANDED_NODE_PLANNING_PROMPT } from '../../../web/lib/ai-guides/expanded-node-planning';
import {
  VISION_AI_GUIDANCE_PROMPT_FROM_RESOURCES,
  VISION_AI_GUIDANCE_PROMPT_FROM_WEBSITE,
} from '../../../web/lib/ai-guides/vision-guidance';
import {
  POST_GEN_CHECKLIST_ALL,
  POST_GEN_CHECKLIST_COMPLETENESS,
  POST_GEN_CHECKLIST_CONDITIONAL,
  POST_GEN_CHECKLIST_DATA_OBJECTS,
  POST_GEN_CHECKLIST_EXPANDED_NODES,
  POST_GEN_CHECKLIST_IA,
  POST_GEN_CHECKLIST_PROCESS_FLOWS,
  POST_GEN_CHECKLIST_SWIMLANE,
  POST_GEN_CHECKLIST_SYSTEM_FLOW,
  POST_GEN_CHECKLIST_TAGS,
  POST_GEN_CHECKLIST_TECHNICAL,
} from '../../../web/lib/ai-checklists/post-generation-index';
import { POST_GEN_CHECKLIST_VISION_IMPORT } from '../../../web/lib/ai-checklists/post-generation-vision';
import { POST_GEN_CHECKLIST_VISION_COMPONENT_LIBRARY } from '../../../web/lib/ai-checklists/post-generation-vision-component-library';

export function buildAiGuideMarkdown(): string {
  return [
    '# Diregram — AI guide (vault copy)',
    '',
    'This file is generated by **Diregram Sync** so your vault always contains the latest AI guidance/checklists.',
    '',
    '## How to use this vault with AI',
    '- Keep each Diregram doc as a standalone `.md` file.',
    '- For **note** docs, the Markdown is the document.',
    '- For **vision** docs, include exactly one `visionjson` fenced block.',
    '- For **grid** docs, include exactly one `gridjson` fenced block.',
    '',
    '## Diagram guidance',
    'Diagram generation uses a Diregram-specific tree format (indentation-based) and additional JSON blocks under a `---` separator.',
    'For the full diagram prompt + bundle, use the “Write AI guide” button (it downloads the bundle from your hosted Diregram).',
    '',
    '## Expanded-node parking lot template (optional)',
    EXPANDED_NODE_PLANNING_PROMPT,
    '',
    '## Vision prompt A — design system resources provided',
    VISION_AI_GUIDANCE_PROMPT_FROM_RESOURCES,
    '',
    '## Vision prompt B — discover from website',
    VISION_AI_GUIDANCE_PROMPT_FROM_WEBSITE,
    '',
    '## Post-generation checklist — ALL (combined)',
    POST_GEN_CHECKLIST_ALL,
    '',
    '## Post-generation checklist — Vision importability',
    POST_GEN_CHECKLIST_VISION_IMPORT,
    '',
    '## Post-generation checklist — Vision component library',
    POST_GEN_CHECKLIST_VISION_COMPONENT_LIBRARY,
    '',
  ].join('\n');
}

export function buildAiGuideBundle(): Array<{ relativePath: string; content: string }> {
  const folder = 'Diregram AI';
  const startHere = [
    '# Diregram AI — Start here',
    '',
    'This folder is generated by **Diregram Sync**.',
    '',
    '## Recommended run order (diagram workflow)',
    '1) Use `01 - Diagram Prompt (FULL).md` if present (downloaded from hosted Diregram).',
    '2) Generate / update your diagram markdown files in your vault.',
    '3) Validate using `10 - Post-generation Checklist (ALL).md`.',
    '4) If you used expanded nodes: use `02 - Expanded Nodes Parking Lot.md` as your second-pass prompt.',
    '5) Re-run the checklist after any fixes.',
    '',
    '## Vision workflow (if you use Vision docs)',
    '1) Pick a prompt: `20 - Vision Prompt A (resources provided).md` or `21 - Vision Prompt B (discover from website).md`.',
    '2) Validate with `22 - Vision Checklist (importability).md` then `23 - Vision Checklist (component library).md`.',
    '',
  ].join('\n');

  return [
    { relativePath: `${folder}/00 - Start Here.md`, content: startHere },
    { relativePath: `${folder}/02 - Expanded Nodes Parking Lot.md`, content: EXPANDED_NODE_PLANNING_PROMPT },
    { relativePath: `${folder}/10 - Post-generation Checklist (ALL).md`, content: POST_GEN_CHECKLIST_ALL },
    { relativePath: `${folder}/11 - Checklist - Technical.md`, content: POST_GEN_CHECKLIST_TECHNICAL },
    { relativePath: `${folder}/12 - Checklist - IA.md`, content: POST_GEN_CHECKLIST_IA },
    { relativePath: `${folder}/13 - Checklist - Expanded Nodes.md`, content: POST_GEN_CHECKLIST_EXPANDED_NODES },
    { relativePath: `${folder}/14 - Checklist - Tags.md`, content: POST_GEN_CHECKLIST_TAGS },
    { relativePath: `${folder}/15 - Checklist - Process Flows.md`, content: POST_GEN_CHECKLIST_PROCESS_FLOWS },
    { relativePath: `${folder}/16 - Checklist - Tech Flow.md`, content: POST_GEN_CHECKLIST_SYSTEM_FLOW },
    { relativePath: `${folder}/17 - Checklist - Conditional.md`, content: POST_GEN_CHECKLIST_CONDITIONAL },
    { relativePath: `${folder}/18 - Checklist - Data Relationship.md`, content: POST_GEN_CHECKLIST_DATA_OBJECTS },
    { relativePath: `${folder}/19 - Checklist - Swimlane.md`, content: POST_GEN_CHECKLIST_SWIMLANE },
    { relativePath: `${folder}/19b - Checklist - Completeness.md`, content: POST_GEN_CHECKLIST_COMPLETENESS },
    { relativePath: `${folder}/20 - Vision Prompt A (resources provided).md`, content: VISION_AI_GUIDANCE_PROMPT_FROM_RESOURCES },
    { relativePath: `${folder}/21 - Vision Prompt B (discover from website).md`, content: VISION_AI_GUIDANCE_PROMPT_FROM_WEBSITE },
    { relativePath: `${folder}/22 - Vision Checklist (importability).md`, content: POST_GEN_CHECKLIST_VISION_IMPORT },
    { relativePath: `${folder}/23 - Vision Checklist (component library).md`, content: POST_GEN_CHECKLIST_VISION_COMPONENT_LIBRARY },
    { relativePath: `${folder}/Diregram AI Guide (combined).md`, content: buildAiGuideMarkdown() },
  ];
}

